# Generated by Django 5.2.4 on 2025-10-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('colour', models.CharField(max_length=100)),
                ('car_type', models.CharField(choices=[('suv', 'suv'), ('sedan', 'Sedan'), ('bus', 'Bus'), ('van', 'Van'), ('luxury-car', 'Luxury-Car')])),
                ('price_per_day', models.FloatField()),
                ('pickup_location', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('unavailable', 'Unavailable')])),
                ('rules', models.TextField()),
                ('seating_capacity', models.IntegerField()),
                ('luggage_capacity', models.IntegerField()),
                ('wheel_drive', models.CharField(choices=[('2-wheel', '2-wheel'), ('4-wheel', '4-wheel')])),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')])),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')])),
                ('photo', models.ImageField(upload_to='media/car_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
