# Generated by Django 5.2.4 on 2025-10-14 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('colour', models.CharField(max_length=100)),
                ('car_type', models.CharField(choices=[('suv', 'suv'), ('sedan', 'Sedan'), ('bus', 'Bus'), ('van', 'Van'), ('luxury-car', 'Luxury-Car')], max_length=20)),
                ('price_per_day', models.FloatField()),
                ('pickup_location', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('unavailable', 'Unavailable')], max_length=20)),
                ('rules', models.TextField()),
                ('seating_capacity', models.IntegerField()),
                ('luggage_capacity', models.IntegerField()),
                ('plate_number', models.CharField(max_length=100, unique=True)),
                ('wheel_drive', models.CharField(choices=[('2-wheel', '2-wheel'), ('4-wheel', '4-wheel')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('photo', models.ImageField(default=None, upload_to='media/car_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='car_car_name_4c7ddc_idx'), models.Index(fields=['model'], name='car_car_model_42d024_idx'), models.Index(fields=['year'], name='car_car_year_02d4b0_idx'), models.Index(fields=['colour'], name='car_car_colour_20e233_idx'), models.Index(fields=['car_type'], name='car_car_car_typ_77252b_idx')],
            },
        ),
    ]
