# Generated by Django 5.2.4 on 2025-10-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='plate_number',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(default=None, upload_to='media/car_photos/'),
        ),
    ]
