# Generated by Django 5.2.4 on 2025-10-05 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_plate_number_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('suv', 'suv'), ('sedan', 'Sedan'), ('bus', 'Bus'), ('van', 'Van'), ('luxury-car', 'Luxury-Car')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('unavailable', 'Unavailable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheel_drive',
            field=models.CharField(choices=[('2-wheel', '2-wheel'), ('4-wheel', '4-wheel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
