# Generated by Django 5.2.4 on 2025-10-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_car_type_alter_car_fuel_type_alter_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
