# Generated by Django 5.2.4 on 2025-10-14 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reservation_type', models.CharField(choices=[('firm', 'Firm'), ('soft', 'Soft')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('modified', 'Modified'), ('active', 'Active'), ('no-show', 'No-Show'), ('dispute', 'Dispute'), ('cancelled', 'Cancelled'), ('overridden', 'Overridden')], default='pending', max_length=20)),
                ('pickup_location', models.TextField()),
                ('dropoff_location', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='reservation_id_2182f0_idx'), models.Index(fields=['user'], name='reservation_user_id_029e9f_idx'), models.Index(fields=['car'], name='reservation_car_id_92ff76_idx'), models.Index(fields=['reservation_type'], name='reservation_reserva_01c4f6_idx'), models.Index(fields=['status'], name='reservation_status_af75b6_idx')],
            },
        ),
    ]
