# Generated by Django 5.2.4 on 2025-10-03 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reservation_type', models.CharField(choices=[('firm', 'Firm'), ('soft', 'Soft')])),
                ('status', models.CharField(choices=[('pennding', 'Pending'), ('confirmed', 'Confirmed'), ('modified', 'Modified'), ('active', 'Active'), ('no-show', 'No-Show'), ('dispute', 'Dispute'), ('cancelled', 'Cancelled')])),
                ('pickup_location', models.TextField()),
                ('dropoff_location', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
