# Generated by Django 5.2.4 on 2025-10-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('modified', 'Modified'), ('active', 'Active'), ('no-show', 'No-Show'), ('dispute', 'Dispute'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
